[project]
name = "workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NiklasBH", email = "nhedeh22@student.aau.dk" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg>=3.3.5",
    "pygrametl>=2.9",
    "python-dotenv>=1.2.3",
]

[project.scripts]
workflow = "workflow:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
